name: fastai_dev
channels:
- fastai
- pytorch
- defaults
- conda-forge
dependencies:
- jupyter
- pytorch>=1.2.0
- torchvision
- matplotlib
- pandas
- requests
- pyyaml
- fastprogress
- pillow
- python>=3.6
- pip
- scikit-learn
- scipy
- spacy
- pyarrow
- scikit-image
- pydicom
